spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel_manage_base
    hikari:
      username: oxlxs
      password: 123456
  data:
    redis:
      port: 6379
      host: localhost
      connect-timeout: 5000
      database: 1

  application:
    name: hotelManagementSysBack
server:
  port: 12417
  jetty:
    threads:
      max: 200
  ssl:
    key-store: C:\Users\lsg30\IdeaProjects\hotelManagementSysBack\src\main\resources\keystore.jks
    key-store-password: 233lsg20040227
    key-store-type: JKS
    key-alias: mykey
#logging:
#  level:
#    org.springframework.security: debug
#    org.springframework.security.access: debug
#    org.springframework.web: debug
#    org.springframework.security.authentication: debug

